name: deploy

on:
  push:
    branches:
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.branch-name-check.outputs.env_name }}
    steps:
      - name: Check branch name
        id: branch-name-check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "env_name=develop" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "env_name=staging" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: check
    name: Deploy app to AWS Fargate
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: load env variables
        shell: bash
        env:
          ENV_VARIABLES: ${{ toJSON(vars) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "Environment Variables:"
          echo "${ENV_VARIABLES}"
          echo "Secrets:"
          echo "${SECRETS}"
