name: deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy app to AWS Fargate
    runs-on: ubuntu-latest

    steps:
      - name: Enable debug logging
        run: echo "AWS_SDK_LOAD_CONFIG=1" >> $GITHUB_ENV
      - name: Configure aws credentials for develop
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GithubActions@${{ github.sha }}
          aws-region: ap-northeast-1
      - name: Verify AWS authentication
        run: aws s3 ls